apiVersion: v1
kind: ServiceAccount
metadata:
  name: simtr-hub-durable-flow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: simtr-hub-durable-flow
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: simtr-hub-durable-flow
subjects:
  - kind: ServiceAccount
    name: simtr-hub-durable-flow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: simtr-hub-durable-flow
