quarkus:
  jackson:
    timezone: America/Sao_Paulo
  http:
    cors: true
    port: 8090
# Logging configuration property 
  log:
    #min-level: TRACE
    min-level: INFO
    level: INFO
    file:
      enable: true
      path: "C:/desenvolvimento/Quarkus/log/server.log"
      rotation:
        max-file-size: 10M
        max-backup-index: 10

    category:
      "br.gov.caixa.simtr":
        level: INFO
      #"com.azure.messaging.servicebus":
      #   level: DEBUG      
      #"com.azure.core.amqp.implementation":
      #   level: DEBUG
      org.hibernate.SQL":
        level: DEBUG
        min-level: DEBUG
      #"org.hibernate.type.descriptor.sql":
      #  level: TRACE
      #  min-level: TRACE
      #"org.apache.http":
      #  level: DEBUG
      #"org.jboss.resteasy.reactive.client.logging":
      #  level: DEBUG
      #"io.quarkus.oidc.runtime.OidcProvider":
      #  level: TRACE
      #  min-level: TRACE
      #"io.quarkus.oidc.runtime.OidcRecorder":
      #  level: TRACE
      #  min-level: TRACE
      #"io.quarkus.oidc.runtime.OidcIdentityProvider":
      #  level: TRACE
      #  min-level: TRACE  
      #"io.quarkus.oidc.client.runtime.OidcClientImpl":
      #  level: TRACE
      #  min-level: TRACE      

 # Datasource configuration property       
  datasource:
    db-kind: oracle  
    jdbc:
      driver: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@//cnpexdadvm01-scan4.extra.caixa.gov.br:1521/cdbd08ngpdb007
      initial-size: 0
      min-size: 0
      max-size: 20 
    username: mtr
    password: ${SIMTR_DB_PASSWORD}
    devservices:
      enabled: false         
  hibernate-orm:
    dialect: org.hibernate.dialect.OracleDialect
    database:
      generation: validate
    #log:
      sql: true
      format-sql: true
      #bind-parameters: true
      #queries-slower-than-ms: 30000
    unsupported-properties:
      "hibernate.query.mutation_strategy": org.hibernate.query.sqm.mutation.internal.inline.InlineMutationStrategy
      "hibernate.hql.bulk_id_strategy.global_temporary.create_tables": false
      "hibernate.hql.bulk_id_strategy.global_temporary.drop_tables": false
  transaction-manager:
    default-transaction-timeout: PT2M   

  tls:
    trust-all: true

#OpenID Connect
  oidc:
    authentication:
     verify-access-token: true
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzcYY/UbvrEldbQRd4TgLeP9bS8YnaL67MZUsfozWRyocBF3S0L7UEbkPaPoCoBnhoRv8VJHp0grqe3mqEmkMuDlt20Vx6q04ADDyS0c8xaU+Ot+g1Pgwjze944ATUjZogEMko6jvqqUGTt/Nt64yCCIaMaTB119vOBExQim7vPHNe/o7hLxh6VBYINxFA/esxjz8j28/uJWIiK0Gvt07Yx7ycn2DJlQHjnH2GzCSUL87AAYmjyYxW2JZaPLLvRlpcHIWrlr9GNtLiq0++xfJ0jFYxQWs1jxhlfXdqr8NE5vfA/RRRjRFnWzFOhIsOnIHPO9eEwwYzCZSoW2zXkFDYwIDAQAB
    auth-server-url: https://login.des.caixa/auth/realms/intranet
    client-id: cli-ser-mtr
    credentials:
      secret: ${SIMTR_OIDC_CLIENT_SECRET}
    internet:
      public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxz8PNmiUW5J1669pWY0APB4flqqDnghAv/QV5DIHyXE39fj9u1DPXbgfDUhUfK0i/B0CHJukbI44Rgo/vuhCMImTnLjS49XuTH6GI4lU/CtdzE/qACMO/GUky73m0Uszo2Bh1wNV+fvw/mMQVAGKj6/qXjSB9npRZKydoXnwGPIepcrqF6KkMJIFtZ+0w35J9SYwgLNezUbAJgs9dq3yMj4ussSfxMFcUC9UKziJJSg0UQfl0fOQGMsrsnUbS2GgXeDqdskbZq9/wfL0ikU2pWf0hKjX+PXtqZI0SVWurVyydc0efbTE7qIlrwF8lWZ8NZ8zcV2oVk7TjoIktZ4zBwIDAQAB 
      auth-server-url: https://logindes.caixa.gov.br/auth/realms/internet
      client-id: cli-ser-mtr
      credentials:
        secret: ${SIMTR_OIDC_INTERNET_CLIENT_SECRET}

#OpenID Connect Client
  oidc-client:
    auth-server-url: ${quarkus.oidc.auth-server-url}
    tls:
      verification: none
    discovery-enabled: false
    token-path: /protocol/openid-connect/token
    client-id: ${quarkus.oidc.client-id}
    #client-id: cli-ser-mtr-outsourcing
    credentials:
      client-secret:
        value: ${quarkus.oidc.credentials.secret}
    connection-timeout: PT15S
    connection-retry-count: 3
    connection-delay: PT20S        
    grant:
      type: CLIENT         

  # Rest Client configuration property
  rest-client:
    #Global Configuration
    connect-timeout: ${simtr.http.establishconnectiontimeout}
    read-timeout: ${simtr.http.sockettimeout}
    #Client Specific Configuration
    siecm-api:
      url: https://siecm.des.caixa/siecm-web/ECM
      scope: jakarta.enterprise.context.ApplicationScoped
      connection-pool-size: 5
      connect-timeout: 1000
      read-timeout: 1000
      proxy-address: none
    cadastro-receita:
#      url: https://portalapi-rest-dev.nprd2.caixa/cadastro-receita
      url: https://api.des.caixa:8443/cadastro-receita
      scope: jakarta.enterprise.context.ApplicationScoped
      connection-pool-size: 5
      connect-timeout: 1000
      read-timeout: 1000
      proxy-address: none
    sinda-api:
      url: https://api.des.caixa:8443
      scope: jakarta.enterprise.context.ApplicationScoped
      connection-pool-size: 15
      connect-timeout: 15000
      read-timeout: 90000
      proxy-address: none
    #logging:
    #  scope: request-response
    #  body-limit: 500

  # JWT RBAC behavior configuration property
  security:
    jaxrs:
      deny-unannotated-endpoints: false
    deny-unannotated-members: false 

  # Smallrye health configuration property
  smallrye-health:
    ui:
      enable: true  

  #  Jacoco report Configuration property
  jacoco:
    report: true
    #title: 
    #includes: **
    excludes: "src/main/java/br/gov/caixa/simtr/mapeamento/**/*, src/test/java/**/*, src/main/java/br/gov/caixa/simtr/excecao/**/*"
    report-location: "jacoco-report"
    
  live-reload:
    instrumentation: true

#Azure Configuration property
service-bus-azure-configuracao:
  http-client-options:
    #proxy-options:
    #  proxy-host: "prd-internet365.caixa"
    #  proxy-port: 80
    connect-timeout: 10000
    write-timeout: 60000
    response-timeout: 60000
    read-timeout: 60000
    maximum-connection-pool-size: 1
    connection-idle-timeout: 60000
  amqp-client-retry-options:
    #max-retries: 3
    #delay: 800
    #max-delay: 60000
    #try-timeout: 60000
    #retry-mode: EXPONENTIAL
    max-retries: 1
    delay: 10
    max-delay: 1000
    try-timeout: 20000    
    retry-mode: FIXED    
  namespace-configuracao:
    namespace: dossiedigitaldes
    connection-string: ${SIMTR_SERVICE_BUS_CONNECTION_STRING}
    #transport-type: AmqpWebSockets    
    transport-type: Amqp
    queues:
      process-every:
        expr: 90s
      queue-config[0]:
        nome: outsourcing-envio-fornecedor-canal
        nome-fisico: outsourcing-envio-fornecedor-canal-locale
        retry: 3
        processor-max-concurrent-calls: 1
        processor-max-dlq-concurrent-calls: 1
        processor-ativar-calls: true
      queue-config[1]:
        nome: outsourcing-envio-fornecedor-processor
        nome-fisico: outsourcing-envio-fornecedor-processor-locale
        retry: 3
        processor-max-concurrent-calls: 1
        processor-max-dlq-concurrent-calls: 1
        processor-ativar-calls: true
      queue-config[2]:
        nome: outsourcing-retorno-fornecedor
        nome-fisico: outsourcing-retorno-fornecedor-locale
        retry: 3
        processor-max-concurrent-calls: 1
        processor-max-dlq-concurrent-calls: 1
        processor-ativar-calls: true
      queue-config[3]:
        nome: outsourcing-retorno-fornecedor-canal
        nome-fisico: outsourcing-retorno-fornecedor-canal-locale
        retry: 3
        processor-max-concurrent-calls: 1
        processor-max-dlq-concurrent-calls: 1
        processor-ativar-calls: true
      queue-config[4]:
        nome: outsourcing-dossie-envio-fornecedor-processor
        nome-fisico: outsourcing-dossie-envio-fornecedor-processor-locale
        retry: 3
        processor-max-concurrent-calls: 1
        processor-max-dlq-concurrent-calls: 1
        processor-ativar-calls: true
      queue-config[5]:
        nome: dossie-produto-efetua-tratamento
        nome-fisico: dossie-produto-efetua-tratamento-locale
        retry: 3
        processor-max-concurrent-calls: 1
        processor-max-dlq-concurrent-calls: 1
        processor-ativar-calls: true
      queue-config[6]:
        nome: outsourcing-documento-envio-ia
        nome-fisico: outsourcing-documento-envio-ia-locale
        retry: 3
        processor-max-concurrent-calls: 1
        processor-max-dlq-concurrent-calls: 1
        processor-ativar-calls: true
      queue-config[7]:
        nome: outsourcing-documento-classificacao-ia
        nome-fisico: outsourcing-documento-classificacao-ia-locale
        retry: 3
        processor-max-concurrent-calls: 1
        processor-max-dlq-concurrent-calls: 1
        processor-ativar-calls: true
      queue-config[8]:
        nome: outsourcing-documento-extracao-ia
        nome-fisico: outsourcing-documento-extracao-ia-locale
        retry: 3
        processor-max-concurrent-calls: 1
        processor-max-dlq-concurrent-calls: 1
        processor-ativar-calls: true
      queue-config[9]:
        nome: outsourcing-documento-validacao-negocial-ia
        nome-fisico: outsourcing-documento-validacao-negocial-ia-locale
        retry: 3
        processor-max-concurrent-calls: 1
        processor-max-dlq-concurrent-calls: 1
        processor-ativar-calls: true

#Azure Configuration property
armazenamento-azure-configuracao:
  storage-account:
    blob-service-client:
      http-client-options:
        #proxy-options:
          #proxy-host: "prd-internet365.caixa"
          #proxy-port: 80
        connect-timeout: 10000
        write-timeout: 60000
        response-timeout: 60000
        read-timeout: 60000
        maximum-connection-pool-size: 500
        connection-idle-timeout: 60000
      blob-endpoint: "https://dossiedigitaldes.blob.core.windows.net/"
      container-max-results-per-page: 20
      storage-shared-key-credential:
        account-name: "dossiedigitaldes"
        account-key: ${KEY_AZURE}
      token-sas-config:
        blob-container-sas-hour-expiry-time: 2


#SIMTR  configuration property
simtr:
  simulador:
    canal: true
    sinda: true
    fornecedor-envio: true
  http:
    establishconnectiontimeout: 15000
    sockettimeout: 30000
  apikey: ${SIMTR_API_KEY}
  documento:
    validacao:
      limite-score-autenticidade: 71
  sinda:
    canal: 61
  proxy:
    https:
      host: proxydes.caixa
      port: 80
      schema: http
    http:
      host: proxydes.caixa
      port: 80
      schema: http     
  atualiza-tipo-documento:
    every:
      expr: 180s
# Envia Documentos Dossie Produto configuration property
  envia-documentos-dossie-produto:
    rotina-ativa: false
    maximo-retries: 3
    every:
      expr: 1m
  atualiza-canal:
    every:
      expr: 90s
  atualiza-etapa:
    every:
      expr: 180s
  log-filtro:
    body-limit: 5000
    req[0]: binario
    req[1]: sas
    res[0]: binario
    res[1]: sas
    client-req[0]: binario
    client-res[0]: binario
  feature:
    usa-novos-campos:
      identidade-fiscal: true
    client-res[0]: binario
document-intelligence-azure-configuracao:
  canal-sso: "mtr-ia-01"
  confidence: 0.80 #Define o limiar de confiança para as operações de classificação e extração de documentos. Documentos com pontuação abaixo desse valor podem ser considerados como não classificados ou com baixa confiabilidade.
  endpoint: ${URL_AISER-DOSSIEDIGITAL}
  key: ${KEY_AISER_DOSSIEDIGITAL}
  classifier-id: classificacao_geral_dossie_digital #ID do classificador de documentos pré-treinado no Azure Document Intelligence. Este ID é usado para identificar qual modelo de classificação de documentos deve ser utilizado para processar os documentos enviados para análise.
  #api-version: 2024-11-30 # Versão da API do Azure
  #base-path: documentintelligence/documentClassifiers  # Caminho base
  timeout:
    initial: 60000 #Define o tempo inicial de espera (timeout) para uma operação em segundos (POST inicial)
    polling: 120000 #Define o tempo máximo de espera (timeout) para as tentativas subsequentes de verificação (Polling/GET) em segundos
