# Converted from doc/properties/application-dev-simtr-hub.yml

%dev.quarkus.jackson.timezone=America/Sao_Paulo
%dev.quarkus.http.cors=true
%dev.quarkus.http.port=8090

# Logging configuration property
%dev.quarkus.log.min-level=INFO
%dev.quarkus.log.level=INFO
%dev.quarkus.log.file.enable=true
%dev.quarkus.log.file.path=C:/desenvolvimento/Quarkus/log/server.log
%dev.quarkus.log.file.rotation.max-file-size=10M
%dev.quarkus.log.file.rotation.max-backup-index=10
%dev.quarkus.log.category."br.gov.caixa.simtr".level=INFO
%dev.quarkus.log.category."org.hibernate.SQL".level=DEBUG
%dev.quarkus.log.category."org.hibernate.SQL".min-level=DEBUG

# Datasource configuration property
%dev.quarkus.datasource.db-kind=oracle
%dev.quarkus.datasource.jdbc.driver=oracle.jdbc.driver.OracleDriver
%dev.quarkus.datasource.jdbc.url=jdbc:oracle:thin:@//cnpexdadvm01-scan4.extra.caixa.gov.br:1521/cdbd08ngpdb007
%dev.quarkus.datasource.jdbc.initial-size=0
%dev.quarkus.datasource.jdbc.min-size=0
%dev.quarkus.datasource.jdbc.max-size=20
%dev.quarkus.datasource.username=mtr
%dev.quarkus.datasource.password=${SIMTR_DB_PASSWORD}
%dev.quarkus.datasource.devservices.enabled=false

%dev.quarkus.hibernate-orm.dialect=org.hibernate.dialect.OracleDialect
%dev.quarkus.hibernate-orm.database.generation=validate
%dev.quarkus.hibernate-orm.database.sql=true
%dev.quarkus.hibernate-orm.database.format-sql=true
%dev.quarkus.hibernate-orm.unsupported-properties."hibernate.query.mutation_strategy"=org.hibernate.query.sqm.mutation.internal.inline.InlineMutationStrategy
%dev.quarkus.hibernate-orm.unsupported-properties."hibernate.hql.bulk_id_strategy.global_temporary.create_tables"=false
%dev.quarkus.hibernate-orm.unsupported-properties."hibernate.hql.bulk_id_strategy.global_temporary.drop_tables"=false

%dev.quarkus.transaction-manager.default-transaction-timeout=PT2M
%dev.quarkus.tls.trust-all=true

# OpenID Connect
%dev.quarkus.oidc.authentication.verify-access-token=true
%dev.quarkus.oidc.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzcYY/UbvrEldbQRd4TgLeP9bS8YnaL67MZUsfozWRyocBF3S0L7UEbkPaPoCoBnhoRv8VJHp0grqe3mqEmkMuDlt20Vx6q04ADDyS0c8xaU+Ot+g1Pgwjze944ATUjZogEMko6jvqqUGTt/Nt64yCCIaMaTB119vOBExQim7vPHNe/o7hLxh6VBYINxFA/esxjz8j28/uJWIiK0Gvt07Yx7ycn2DJlQHjnH2GzCSUL87AAYmjyYxW2JZaPLLvRlpcHIWrlr9GNtLiq0++xfJ0jFYxQWs1jxhlfXdqr8NE5vfA/RRRjRFnWzFOhIsOnIHPO9eEwwYzCZSoW2zXkFDYwIDAQAB
%dev.quarkus.oidc.auth-server-url=https://login.des.caixa/auth/realms/intranet
%dev.quarkus.oidc.client-id=cli-ser-mtr
%dev.quarkus.oidc.credentials.secret=${SIMTR_OIDC_CLIENT_SECRET}
%dev.quarkus.oidc.internet.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxz8PNmiUW5J1669pWY0APB4flqqDnghAv/QV5DIHyXE39fj9u1DPXbgfDUhUfK0i/B0CHJukbI44Rgo/vuhCMImTnLjS49XuTH6GI4lU/CtdzE/qACMO/GUky73m0Uszo2Bh1wNV+fvw/mMQVAGKj6/qXjSB9npRZKydoXnwGPIepcrqF6KkMJIFtZ+0w35J9SYwgLNezUbAJgs9dq3yMj4ussSfxMFcUC9UKziJJSg0UQfl0fOQGMsrsnUbS2GgXeDqdskbZq9/wfL0ikU2pWf0hKjX+PXtqZI0SVWurVyydc0efbTE7qIlrwF8lWZ8NZ8zcV2oVk7TjoIktZ4zBwIDAQAB
%dev.quarkus.oidc.internet.auth-server-url=https://logindes.caixa.gov.br/auth/realms/internet
%dev.quarkus.oidc.internet.client-id=cli-ser-mtr
%dev.quarkus.oidc.internet.credentials.secret=${SIMTR_OIDC_INTERNET_CLIENT_SECRET}

# OpenID Connect Client
%dev.quarkus.oidc-client.auth-server-url=${quarkus.oidc.auth-server-url}
%dev.quarkus.oidc-client.tls.verification=none
%dev.quarkus.oidc-client.discovery-enabled=false
%dev.quarkus.oidc-client.token-path=/protocol/openid-connect/token
%dev.quarkus.oidc-client.client-id=${quarkus.oidc.client-id}
%dev.quarkus.oidc-client.credentials.client-secret.value=${quarkus.oidc.credentials.secret}
%dev.quarkus.oidc-client.connection-timeout=PT15S
%dev.quarkus.oidc-client.connection-retry-count=3
%dev.quarkus.oidc-client.connection-delay=PT20S
%dev.quarkus.oidc-client.grant.type=CLIENT

# Rest Client configuration property
%dev.quarkus.rest-client.connect-timeout=${simtr.http.establishconnectiontimeout}
%dev.quarkus.rest-client.read-timeout=${simtr.http.sockettimeout}
%dev.quarkus.rest-client.siecm-api.url=https://siecm.des.caixa/siecm-web/ECM
%dev.quarkus.rest-client.siecm-api.scope=jakarta.enterprise.context.ApplicationScoped
%dev.quarkus.rest-client.siecm-api.connection-pool-size=5
%dev.quarkus.rest-client.siecm-api.connect-timeout=1000
%dev.quarkus.rest-client.siecm-api.read-timeout=1000
%dev.quarkus.rest-client.siecm-api.proxy-address=none
%dev.quarkus.rest-client.cadastro-receita.url=https://api.des.caixa:8443/cadastro-receita
%dev.quarkus.rest-client.cadastro-receita.scope=jakarta.enterprise.context.ApplicationScoped
%dev.quarkus.rest-client.cadastro-receita.connection-pool-size=5
%dev.quarkus.rest-client.cadastro-receita.connect-timeout=1000
%dev.quarkus.rest-client.cadastro-receita.read-timeout=1000
%dev.quarkus.rest-client.cadastro-receita.proxy-address=none
%dev.quarkus.rest-client.sinda-api.url=https://api.des.caixa:8443
%dev.quarkus.rest-client.sinda-api.scope=jakarta.enterprise.context.ApplicationScoped
%dev.quarkus.rest-client.sinda-api.connection-pool-size=15
%dev.quarkus.rest-client.sinda-api.connect-timeout=15000
%dev.quarkus.rest-client.sinda-api.read-timeout=90000
%dev.quarkus.rest-client.sinda-api.proxy-address=none
%dev.quarkus.rest-client.gestao-documento.url=https://api.des.caixa:8443/simtr
%dev.quarkus.rest-client.gestao-documento.scope=jakarta.enterprise.context.ApplicationScoped
%dev.quarkus.rest-client.gestao-documento.connection-pool-size=5
%dev.quarkus.rest-client.gestao-documento.connect-timeout=1000
%dev.quarkus.rest-client.gestao-documento.read-timeout=1000
%dev.quarkus.rest-client.gestao-documento.proxy-address=none

# JWT RBAC behavior configuration property
%dev.quarkus.security.jaxrs.deny-unannotated-endpoints=false
%dev.quarkus.security.deny-unannotated-members=false

# Smallrye health configuration property
%dev.quarkus.smallrye-health.ui.enable=true

# Jacoco report Configuration property
%dev.quarkus.jacoco.report=true
%dev.quarkus.jacoco.excludes=src/main/java/br/gov/caixa/simtr/mapeamento/**/*, src/test/java/**/*, src/main/java/br/gov/caixa/simtr/excecao/**/*
%dev.quarkus.jacoco.report-location=jacoco-report
%dev.quarkus.live-reload.instrumentation=true

# Azure Service Bus configuration property
%dev.service-bus-azure-configuracao.http-client-options.connect-timeout=10000
%dev.service-bus-azure-configuracao.http-client-options.write-timeout=60000
%dev.service-bus-azure-configuracao.http-client-options.response-timeout=60000
%dev.service-bus-azure-configuracao.http-client-options.read-timeout=60000
%dev.service-bus-azure-configuracao.http-client-options.maximum-connection-pool-size=1
%dev.service-bus-azure-configuracao.http-client-options.connection-idle-timeout=60000
%dev.service-bus-azure-configuracao.amqp-client-retry-options.max-retries=1
%dev.service-bus-azure-configuracao.amqp-client-retry-options.delay=10
%dev.service-bus-azure-configuracao.amqp-client-retry-options.max-delay=1000
%dev.service-bus-azure-configuracao.amqp-client-retry-options.try-timeout=20000
%dev.service-bus-azure-configuracao.amqp-client-retry-options.retry-mode=FIXED
%dev.service-bus-azure-configuracao.namespace-configuracao.namespace=dossiedigitaldes
%dev.service-bus-azure-configuracao.namespace-configuracao.connection-string=${SIMTR_SERVICE_BUS_CONNECTION_STRING}
%dev.service-bus-azure-configuracao.namespace-configuracao.transport-type=Amqp
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.process-every.expr=90s
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[0].nome=outsourcing-envio-fornecedor-canal
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[0].nome-fisico=outsourcing-envio-fornecedor-canal-locale
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[0].retry=3
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[0].processor-max-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[0].processor-max-dlq-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[0].processor-ativar-calls=true
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[1].nome=outsourcing-envio-fornecedor-processor
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[1].nome-fisico=outsourcing-envio-fornecedor-processor-locale
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[1].retry=3
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[1].processor-max-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[1].processor-max-dlq-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[1].processor-ativar-calls=true
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[2].nome=outsourcing-retorno-fornecedor
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[2].nome-fisico=outsourcing-retorno-fornecedor-locale
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[2].retry=3
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[2].processor-max-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[2].processor-max-dlq-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[2].processor-ativar-calls=true
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[3].nome=outsourcing-retorno-fornecedor-canal
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[3].nome-fisico=outsourcing-retorno-fornecedor-canal-locale
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[3].retry=3
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[3].processor-max-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[3].processor-max-dlq-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[3].processor-ativar-calls=true
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[4].nome=outsourcing-dossie-envio-fornecedor-processor
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[4].nome-fisico=outsourcing-dossie-envio-fornecedor-processor-locale
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[4].retry=3
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[4].processor-max-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[4].processor-max-dlq-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[4].processor-ativar-calls=true
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[5].nome=dossie-produto-efetua-tratamento
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[5].nome-fisico=dossie-produto-efetua-tratamento-locale
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[5].retry=3
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[5].processor-max-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[5].processor-max-dlq-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[5].processor-ativar-calls=true
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[6].nome=outsourcing-documento-envio-ia
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[6].nome-fisico=outsourcing-documento-envio-ia-locale
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[6].retry=3
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[6].processor-max-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[6].processor-max-dlq-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[6].processor-ativar-calls=true
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[7].nome=outsourcing-documento-classificacao-ia
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[7].nome-fisico=outsourcing-documento-classificacao-ia-locale
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[7].retry=3
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[7].processor-max-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[7].processor-max-dlq-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[7].processor-ativar-calls=true
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[8].nome=outsourcing-documento-extracao-ia
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[8].nome-fisico=outsourcing-documento-extracao-ia-locale
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[8].retry=3
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[8].processor-max-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[8].processor-max-dlq-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[8].processor-ativar-calls=true
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[9].nome=outsourcing-documento-validacao-negocial-ia
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[9].nome-fisico=outsourcing-documento-validacao-negocial-ia-locale
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[9].retry=3
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[9].processor-max-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[9].processor-max-dlq-concurrent-calls=1
%dev.service-bus-azure-configuracao.namespace-configuracao.queues.queue-config[9].processor-ativar-calls=true

# Azure Storage configuration property
%dev.armazenamento-azure-configuracao.storage-account.blob-service-client.http-client-options.connect-timeout=10000
%dev.armazenamento-azure-configuracao.storage-account.blob-service-client.http-client-options.write-timeout=60000
%dev.armazenamento-azure-configuracao.storage-account.blob-service-client.http-client-options.response-timeout=60000
%dev.armazenamento-azure-configuracao.storage-account.blob-service-client.http-client-options.read-timeout=60000
%dev.armazenamento-azure-configuracao.storage-account.blob-service-client.http-client-options.maximum-connection-pool-size=500
%dev.armazenamento-azure-configuracao.storage-account.blob-service-client.http-client-options.connection-idle-timeout=60000
%dev.armazenamento-azure-configuracao.storage-account.blob-service-client.blob-endpoint=https://dossiedigitaldes.blob.core.windows.net/
%dev.armazenamento-azure-configuracao.storage-account.blob-service-client.container-max-results-per-page=20
%dev.armazenamento-azure-configuracao.storage-account.blob-service-client.storage-shared-key-credential.account-name=dossiedigitaldes
%dev.armazenamento-azure-configuracao.storage-account.blob-service-client.storage-shared-key-credential.account-key=${KEY_AZURE}
%dev.armazenamento-azure-configuracao.storage-account.blob-service-client.token-sas-config.blob-container-sas-hour-expiry-time=2

# SIMTR configuration property
%dev.simtr.simulador.canal=true
%dev.simtr.simulador.sinda=true
%dev.simtr.simulador.fornecedor-envio=true
%dev.arvore-documento.simulador.gestao-documento.habilitado=true
%dev.simtr.http.establishconnectiontimeout=15000
%dev.simtr.http.sockettimeout=30000
%dev.simtr.apikey=${SIMTR_API_KEY}
%dev.simtr.documento.validacao.limite-score-autenticidade=71
%dev.simtr.sinda.canal=61
%dev.simtr.proxy.https.host=proxydes.caixa
%dev.simtr.proxy.https.port=80
%dev.simtr.proxy.https.schema=http
%dev.simtr.proxy.http.host=proxydes.caixa
%dev.simtr.proxy.http.port=80
%dev.simtr.proxy.http.schema=http
%dev.simtr.atualiza-tipo-documento.every.expr=180s
%dev.simtr.envia-documentos-dossie-produto.rotina-ativa=false
%dev.simtr.envia-documentos-dossie-produto.maximo-retries=3
%dev.simtr.envia-documentos-dossie-produto.every.expr=1m
%dev.simtr.atualiza-canal.every.expr=90s
%dev.simtr.atualiza-etapa.every.expr=180s
%dev.simtr.log-filtro.body-limit=5000
%dev.simtr.log-filtro.req[0]=binario
%dev.simtr.log-filtro.req[1]=sas
%dev.simtr.log-filtro.res[0]=binario
%dev.simtr.log-filtro.res[1]=sas
%dev.simtr.log-filtro.client-req[0]=binario
%dev.simtr.log-filtro.client-res[0]=binario
%dev.simtr.feature.usa-novos-campos.identidade-fiscal=true
%dev.simtr.feature.client-res[0]=binario

%dev.document-intelligence-azure-configuracao.canal-sso=mtr-ia-01
%dev.document-intelligence-azure-configuracao.confidence=0.80
%dev.document-intelligence-azure-configuracao.endpoint=${URL_AISER_DOSSIEDIGITAL}
%dev.document-intelligence-azure-configuracao.key=${KEY_AISER_DOSSIEDIGITAL}
%dev.document-intelligence-azure-configuracao.classifier-id=classificacao_geral_dossie_digital
%dev.document-intelligence-azure-configuracao.timeout.initial=60000
%dev.document-intelligence-azure-configuracao.timeout.polling=120000
